#!/bin/bash
# Text (small): size(no flags) <= BOUND?

RUN="/usr/bin/valgrind -q"

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t04x
BOUND=600

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

ESIZE=`wc -c < $EOUT`

if test $ESIZE -gt $BOUND -o -v DEBUG_SCRIPT ; then
  echo "size() = $ESIZE > $BOUND"
fi
