#!/bin/bash
# size(no flags) <= BOUND?

RUN="/usr/bin/valgrind -q"

EFLAG=
FILE=/c/cs323/Style/C-Stanford
BOUND=4000

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

$RUN ./encode $EFLAG < $FILE > $EOUT
$RUN ./decode        < $EOUT > $DOUT
/usr/bin/cmp - $FILE < $DOUT

ESIZE=`wc -c < $EOUT`

if test $ESIZE -gt $BOUND -o -v DEBUG_SCRIPT ; then
  echo "size() = $ESIZE > $BOUND"
fi
