#!/bin/bash
# Is all storage reachable on exit?
# Reprise of Tests #01 and #07

RUN="/usr/bin/valgrind -q --leak-check=yes"

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t01x
cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT

echo =====

EFLAG="-m 13"
FILE=/c/cs323/Doc/logic.1
cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
