#!/bin/bash
# Text (small) correct?

RUN="/usr/bin/valgrind -q"

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t19x

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

ulimit -t 4
trap  "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE
