#!/bin/bash
# Text (huge) correct?

RUN=/c/cs323/bin/run

EFLAG=
FILE=/c/cs323/Doc/warAndPeace

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE
