#!/bin/bash
# size(-m 14) << size(-m 13)?

RUN=/c/cs323/bin/run

EFLAG="-m 14"
XFLAG="-m 13"
FILE=/bin/more
FUDGE=95

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$
XOUT=/tmp/lzw.x.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT $XOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

cat $FILE | $RUN ./encode $XFLAG > $XOUT
cat $XOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

ESIZE=`wc -c < $EOUT`
XSIZE=`wc -c < $XOUT`
BOUND=$(($FUDGE * $XSIZE / 100))

if test $ESIZE -gt $BOUND -o -v DEBUG_SCRIPT ; then
  echo "size($EFLAG) = $ESIZE > $BOUND = .$FUDGE * $XSIZE = .$FUDGE * size($XFLAG)"
fi
