#!/bin/bash
# size(-m 15) in [LOWER,UPPER]?:

RUN=/c/cs323/bin/run

EFLAG="-m 15"
FILE=/c/cs323/Doc/words
LOWER=100000
UPPER=120000

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

ESIZE=`wc -c < $EOUT`

if test $ESIZE -lt $LOWER -o -v DEBUG_SCRIPT ; then
  echo "size($EFLAG) = $ESIZE < $LOWER"
fi

if test $ESIZE -gt $UPPER -o -v DEBUG_SCRIPT ; then
  echo "size($EFLAG) = $ESIZE > $UPPER"
fi
