#!/bin/bash
# Run as encode or ./decode/encode or ...

RUN=/c/cs323/bin/run

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t01x

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

TDIR=/tmp/lzw.t.$USER.$$
/c/cs323/bin/Exist $TDIR && exit

ulimit -t 4
trap "/bin/rm -rf $EOUT $DOUT $TDIR" 0 1 2 3 9 15

cat $FILE | $RUN   encode $EFLAG > $EOUT
cat $EOUT | $RUN   decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

mkdir $TDIR
/bin/ln -s `pwd` $TDIR/encode
/bin/ln -s `pwd` $TDIR/decode

cat $FILE | $RUN $TDIR/./decode/encode $EFLAG > $EOUT
cat $EOUT | $RUN $TDIR/./encode/decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE
