#!/bin/bash
# Illegal flags

RUN=/c/cs323/bin/run

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t01x

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT" 0 1 2 3 9 15

# Illegal variations on -m MAXBITS

($RUN ./encode -m           < $FILE > $EOUT) |& wc -l
echo -----

($RUN ./encode -m12         < $FILE > $EOUT) |& wc -l
echo -----

($RUN ./encode -maxbits 12  < $FILE > $EOUT) |& wc -l
echo -----

($RUN ./encode +m 12        < $FILE > $EOUT) |& wc -l
echo -----

# Illegal options for encode

($RUN ./encode -q           < $FILE > $EOUT) |& wc -l
echo -----

# Valid flag

($RUN ./encode -m 12        < $FILE > $EOUT) |& wc -l
echo -----

# Illegal options for decode

($RUN ./decode -m 12        < $EOUT > $DOUT) |& wc -l
