#!/bin/bash
# Reachability under -m and -p
#   Is all storage reachable on exit?

RUN="/usr/bin/valgrind -q --leak-check=yes"

EFLAG="-p"
XFLAG=
FILE=/c/cs323/Doc/snark.1
FUDGE=99

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$
XOUT=/tmp/lzw.x.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT $XOUT" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT

#####
# Verify that -p is implemented

cat $FILE | $RUN ./encode $XFLAG > $XOUT

ESIZE=`wc -c < $EOUT`
XSIZE=`wc -c < $XOUT`
BOUND=$(($FUDGE * $XSIZE / 100))

if test $ESIZE -gt $BOUND -o -v DEBUG_SCRIPT ; then
  echo "size($EFLAG) = $ESIZE > $BOUND = .$FUDGE * $XSIZE = .$FUDGE * size($XFLAG)"
fi
