#!/bin/bash
# Feed empty file to decode (graceful)

RUN="/usr/bin/valgrind -q"

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t01x

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$
ERRS=/tmp/lzw.errs.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT $ERRS" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

echo =====

#####
# Input to decode is empty file
cat /dev/null | \
 $RUN --log-file=$ERRS ./decode &> /dev/null
wc -l < $ERRS
