#!/bin/bash
# Garble input to decode

RUN="/usr/bin/valgrind -q"

EFLAG=
FILE=/c/cs323/Hwk4/Tests/t01x

EOUT=/tmp/lzw.e.$USER.$$
DOUT=/tmp/lzw.d.$USER.$$
ERRS=/tmp/lzw.errs.$USER.$$

ulimit -t 4
trap "/bin/rm -f $EOUT $DOUT $ERRS" 0 1 2 3 9 15

cat $FILE | $RUN ./encode $EFLAG > $EOUT
cat $EOUT | $RUN ./decode        > $DOUT
cat $DOUT | /usr/bin/cmp - $FILE

echo =====

#####
# Input to decode is non-encoded file
cat $FILE | \
 $RUN --log-file=$ERRS ./decode &> /dev/null
wc -l < $ERRS

echo =====

#####
# Input to decode is garbled version of encoded file
/c/cs323/Hwk4/Tests/garble 200 < $EOUT | \
 $RUN --log-file=$ERRS ./decode &> /dev/null
wc -l < $ERRS

echo =====

#####
# Input to decode is encoded file with every second group of 50 chars deleted
/c/cs323/Hwk4/Tests/chop 50 < $EOUT | \
 $RUN --log-file=$ERRS ./decode &> /dev/null
wc -l < $ERRS
